### ISSUE TITLE
Too many redirects on the root path of the test environment domain

### ISSUE THREAD

**Issue by pedrocasi** [Tecnativa/doodba-copier-template#239] opened 2021-04-06 09:45 UTC
First things first: thank you all for this excelent project!

I'm using the devel and prod environments and everything works fine. However, on the test environment, I'm experiencing a "bug" and I wonder if you can acknowledge it. The symptom is this: all paths of my domain work fine except for the root path which returns ERR_TOO_MANY_REDIRECTS. In other words: whatever.mydomain.com/anypath works but whatever.mydomain.com doesn't.

The config is pretty much vanilla: unmodified inverseproxy and globalwhitelist; no modification of test.yaml after doodba copier template rendering.  Answers file contains a pretty simple domain setup:
domains_test:
  - hosts:
      - whatever.mydomain.com

Thank you!

**Comment by Yajo** [comment] 2021-04-07 10:20
Hi there!

Thanks for taking the time to report the problem, but **it seems like this is not exactly a bug** in this project's code and/or scope. It is more likely a problem on your specific deployment, instance or configuration.

Doodba is a project that sews many others together, such as:

- [click-odoo-contrib](https://github.com/acsone/click-odoo-contrib)
- [Copier](https://github.com/pykong/copier)
- [Docker Compose](https://docs.docker.com/compose/)
- [Docker](https://www.docker.com/)
- [Git Aggregator](https://github.com/acsone/git-aggregator)
- [Git](https://git-scm.com/)
- [Gitlab](https://gitlab.com/)
- [OCA](https://odoo-community.org/)
- [Odoo](https://www.odoo.com/)
- [Traefik](https://traefik.io)

When you use Doodba, you are expected to know those tools. Although this project includes some documentation that is specific for some of those components, we don't aim to replace their own documentation or support channels, which might be documentation, a mailing list, a chat room, a help forum, commercial support, etc.


It seems your problem is more related to Traefik.

I hope you can get proper help there. If you find out that your problem was finally caused by Doodba itself or that some if our docs are missing, incomplete, outdated or confusing, please feel free to reopen this issue, open a new one, or even contribute a PR to improve the situation.

To keep the bug tracker clean and focused, I'm going to close this issue. I hope you understand and don't take that personally. 😊

Have a nice day!

**Closed by Yajo** 2021-04-07 10:20 UTC

**Comment by netosjb** [comment] 2021-10-13 03:56
@pedrocasi

 I have the same problem, did you find any solution?

**Comment by pedrocasi** [comment] 2021-10-13 09:29
Hi Antônio,

I didn't find a clean solution but I got it working. A brief explanation is required: the problem is related to traefik and the paths without crawlers (or forbidden crawlers) parameters on version 13.0 onwards. These are a way for you to define which paths of your site you don't want search engines to "see". This is a known issue in every environment:  #166. My workaround for this is to use **paths_without_crawlers: null** in my copier-answers.yml file.

In the test environment, the copier template system ignores the paths_without_crawlers parameter and sets up / for that matter. The intention is good: prevent your whole testing environment to be indexed by search engines. But then it hits the issue that I described before. My solution was to modify test.yaml.jinja on my fork of the doodba-copier-template project. Replace

```

    labels:
      doodba.domain.main: {{ macros.first_main_domain(domains_test)|tojson }}
      {%- if odoo_proxy == "traefik" and domains_test %}
      traefik.enable: "true"
      {{- traefik1_labels.odoo(domains_test, ["/"]) }}
      {{- traefik2_labels.odoo(
        domains_test,
        cidr_whitelist,
        _key,
        odoo_version,
        ["/"],
        project_name,
      ) }}
    {%- endif %}
```

with

```
    labels:
      doodba.domain.main: {{ macros.first_main_domain(domains_test)|tojson }}
      {%- if odoo_proxy == "traefik" and domains_test %}
      traefik.enable: "true"
      {{- traefik1_labels.odoo(domains_test, paths_without_crawlers) }}
      {{- traefik2_labels.common_middlewares(_key, cidr_whitelist) }}
      {{- traefik2_labels.odoo(
        domains_test,
        cidr_whitelist,
        _key,
        odoo_version,
        paths_without_crawlers,
        project_name,
      ) }}
    {%- endif %}
```

and don't forget to keep the null on the paths_without_crawlers parameter. Be aware that this exposes your test environment to the web crawlers so you should complement the config with a working CIDR whitelist or deploy on an internal network. Good luck. Let me know if you happen to find a cleaner solution.
