### ISSUE TITLE
[question] Why does the test environment force me to use / web?

### ISSUE THREAD

**Issue by estraka** [Tecnativa/doodba-copier-template#118] opened 2020-09-21 07:37 UTC
Hello, when I try to use the test environment, if I do not use [ip]/web, it does not work for me,  I don't go to the web. This is a problem when I try to test the website, because there are links that fail. In production it does not behave like this, and I had understood that the behavior should be the same, except when sending emails ...
How should I avoid the /web?

**Comment by Yajo** [comment] 2020-09-21 08:13
Hi there.

Thanks for your report, but it's lacking enough information and it cannot be fixed until it's provided. I close it for that reason. The test environment works for me and I cannot reproduce that problem you say.

If you provide the requested information later, please reopen it.

Thank you!

**Closed by Yajo** 2020-09-21 08:13 UTC

**Comment by estraka** [comment] 2020-10-06 10:06
Hi!
I run copier and report test domain with:
- hosts: [cns.ddns.net, 192.168.0.100]
The test environment is installed on clean local Debian Linux. Previously it was the server where the production environment was installed that has been migrated to a VPS and did not present these problems. I had never used test environment.

When I try to access directly by the IP or by the URL of ddns, if I don't add /web behind, the browser gives me an error saying that the number of redirects is very high. I have not all generated test.yaml. With the production URL this does not happen to me.
I have not analyzed the test.yaml that is generated for Traefik because I don't know anything about it.

<img width="610" alt="Captura de pantalla 2020-10-06 a las 11 51 20" src="https://user-images.githubusercontent.com/29714115/95188173-5b373680-07cc-11eb-87f8-3cdc53d3832c.png">
