### ISSUE TITLE
invoke git_aggregate with --force.

### ISSUE THREAD

**Issue by manuelcalerosolis** [Tecnativa/doodba-copier-template#75] opened 2020-06-30 09:27 UTC
Some repositories appear dirty to me without knowing the cause, downloading only for version 13.0 without any added repository.

git-aggregat has the --force option to continue even if there are dirty repositories.

How can we incorporate this parameter into invoke?

Regards.

**Comment by Yajo** [comment] 2020-06-30 09:51
First it has to be supported in [the autoaggregate script](https://github.com/Tecnativa/doodba/blob/6b0a0050fe20645dd18c25d97e4ac6f4ed71c2be/bin/autoaggregate#L29-L69).

Then we have to add it here to [the task](https://github.com/Tecnativa/doodba-copier-template/blob/094c46a60854b9575dccf62f998057b73ea2dea3/tasks_downstream.py#L94-L112).

Then I'll release a new template version and you'll have to update your subproject.

PRs welcome!

**Comment by manuelcalerosolis** [comment] 2020-07-02 10:55
I don't know how doodba works inside, I am trying to see the code and understand it, but I still lack knowledge, which I hope to acquire.

On the subject of --force maybe it should be included as an option, everyone doesn't like it anyway.

I would like to know how I can do a fork (that if I can do it), and test the changes locally. Can I look at some documentation about it?

Thank you very much for sharing this great project with the community.

**Comment by pedrobaeza** [comment] 2020-07-02 10:56
@Yajo is on holidays. For forking, you have to fork the project and publish your fork in a Docker registry, but that's out of the scope of this issue tracker.

**Comment by manuelcalerosolis** [comment] 2020-07-02 11:00
Fork is not the problem.

I hope @Yajo enjoys his well-deserved vacation.

**Comment by pedrobaeza** [comment] 2020-07-02 11:02
What is the problem then?

**Comment by manuelcalerosolis** [comment] 2020-07-02 18:43
The problem is my lack of knowledge to carry out a PR that includes that modifier, I still have a lot to learn.

**Comment by pedrobaeza** [comment] 2020-07-02 18:45
OK, then you can do the reset manually meanwhile in your local environment. I don't get anyway why you get to that situation, as normal use shouldn't lead to that.

**Comment by manuelcalerosolis** [comment] 2020-07-03 11:23
I don't know the reason but it always tells me it's dirty addons / website_membership / __ init__.py

odoo_1  | From https://github.com/OCA/OCB
odoo_1  |  * branch              13.0       -> FETCH_HEAD
odoo_1  |    2b58db81..3b43934c  13.0       -> ocb/13.0
odoo_1  | (INFO) [11:17:27] git_aggregator.repo  odoo   Checking repo status
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/local/lib/python3.6/site-packages/git_aggregator/main.py", line 204, in aggregate_repo
odoo_1  |     repo.aggregate()
odoo_1  |   File "/usr/local/lib/python3.6/site-packages/git_aggregator/repo.py", line 189, in aggregate
odoo_1  |     self._reset_to(origin["remote"], origin["ref"])
odoo_1  |   File "/usr/local/lib/python3.6/site-packages/git_aggregator/repo.py", line 236, in _reset_to
odoo_1  |     self._check_status()
odoo_1  |   File "/usr/local/lib/python3.6/site-packages/git_aggregator/repo.py", line 223, in _check_status
odoo_1  |     raise DirtyException(status)
odoo_1  | git_aggregator.exception.DirtyException:  M addons/website_membership/__init__.py

**Comment by pedrobaeza** [comment] 2020-07-03 11:26
That's probably due to permissions in the filesystem. Probably you are not using a native Linux filesystem, but other like FAT, NTFS, Samba, etc.

Anyway, closing this for having the issue tracker as there's no plan for now of adding this option and the source problem comes from other thing.

**Comment by Yajo** [comment] 2020-07-22 07:14
Hi, the issue is still valid. When you run `inv git-aggregate` it will fail if there's a dirty git repo. That's a feature, otherwise the command could blindly remove some of your changes forever, and it's meant to be run in a development environment, so that's not very cool.

Adding a `--force` option makes sense in case you're conscient about what will happen.

**Comment by pedrobaeza** [comment] 2020-07-22 07:24
I don't like to keep issues for wishlists forever if nobody is going to attend it, so please put this in any kind of roadmap and close the issue.

**Comment by manuelcalerosolis** [comment] 2020-07-28 07:09
I've already solved my problems with dirty repositories, if the --force option can backfire, you can close this issue.

**Closed** 2020-08-04 08:51 UTC
Labels: help wanted
