### ISSUE TITLE
odoo signature Uncaught TypeError: node.className.match is not a function

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#180] opened 2020-11-18 14:02 UTC
I know this is an old closed issue but I still has the issue with odoo signature widget and cannot fix it.

Odoo 13

I beleive this is not a bug on code because I have develop ambient with previous version of copier and on productive environment with newest copier template version site i have the issue.

When I do click on signature widget I get this message:

Uncaught TypeError: node.className.match is not a function

https://myserver.com/web/content/618-e72739b/web_editor.assets_wysiwyg.js:444

Traceback:

TypeError: node.className.match is not a function

    at Object.dom.isVoid (https://myserver.com/web/content/618-e72739b/web_editor.assets_wysiwyg.js:444:2184)
    at dom.isNotBreakable (https://myserver.com/web/content/616-d856350/web_editor.summernote.js:504:1012)
    at WrappedRange.range.WrappedRange.reRange (https://myserver.com/web/content/616-d856350/web_editor.summernote.js:507:507)
    at reRangeSelect (https://myserver.com/web/content/618-e72739b/web_editor.assets_wysiwyg.js:460:99)
    at HTMLDocument.summernote_mouseup (https://myserver.com/web/content/618-e72739b/web_editor.assets_wysiwyg.js:463:274)
    at HTMLDocument.dispatch (https://myserver.com/web/content/613-c52537e/web.assets_common.js:1024:447)
    at HTMLDocument.elemData.handle (https://myserver.com/web/content/613-c52537e/web.assets_common.js:1010:166)

Some insight?

**Comment by carlosecv** [comment] 2020-11-19 02:05
I think this is because traefik labels missing options, im not good on traefik labels jet.

My Odoo log says:

odoo.http: <function Binary.get_fonts at 0x7ff4208b09d8>, /web/sign/get_fonts: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

**Comment by carlosecv** [comment] 2020-11-19 02:13
Its good to mention that with old labels the issue is not present but n new labels configuration is appearing.

My old traefik labels:

traefik.longpolling.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:${DOMAIN_PROD}"
      traefik.forbid-crawlers.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}"
      traefik.alt-0.frontend.redirect.regex: "^(.*)://${DOMAIN_PROD_ALT_0}/(.*)$$"
      traefik.alt-0.frontend.redirect.replacement: "$$1://${DOMAIN_PROD}/$$2"
      traefik.alt-0.frontend.rule: "Host:${DOMAIN_PROD_ALT_0}"
      traefik.alt-1.frontend.redirect.regex: "^(.*)://${DOMAIN_PROD_ALT_1}/(.*)$$"
      traefik.alt-1.frontend.redirect.replacement: "$$1://${DOMAIN_PROD}/$$2"
      traefik.alt-1.frontend.rule: "Host:${DOMAIN_PROD_ALT_1}"
      # Main service
      traefik.http.middlewares.recpa-prod-13-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.recpa-prod-13-0-prod-compress.compress: "true"
      traefik.http.routers.recpa-prod-13-0-prod-main.entrypoints: "web-main"
      traefik.http.routers.recpa-prod-13-0-prod-main.middlewares:
        recpa-prod-13-0-prod-buffering,
        recpa-prod-13-0-prod-compress
      traefik.http.routers.recpa-prod-13-0-prod-main.rule: "host(`${DOMAIN_PROD}`)"
      traefik.http.routers.recpa-prod-13-0-prod-main.service: "recpa-prod-13-0-prod-main"
      traefik.http.routers.recpa-prod-13-0-prod-main.tls: "true"
      traefik.http.routers.recpa-prod-13-0-prod-main.tls.certresolver: "letsencrypt"
      traefik.http.services.recpa-prod-13-0-prod-main.loadbalancer.server.port: 8069
      # Redirect alternative domains to main domain
      traefik.http.middlewares.recpa-prod-13-0-prod-redirect2main.redirectregex.regex: "^https://([^/]+)/(.*)$$"
      traefik.http.middlewares.recpa-prod-13-0-prod-redirect2main.redirectregex.replacement: "https://${DOMAIN_PROD}/$${2}"
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.entrypoints: "web-main"
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.middlewares:
        recpa-prod-13-0-prod-compress,
        recpa-prod-13-0-prod-redirect2main
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.rule:
        Host(`${DOMAIN_PROD_ALT_0}`, `${DOMAIN_PROD_ALT_1}`)
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.service: "recpa-prod-13-0-prod-main"
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.tls: "true"
      traefik.http.routers.recpa-prod-13-0-prod-altdomains.tls.certresolver: "letsencrypt"
      # Longpolling service
      traefik.http.routers.recpa-prod-13-0-prod-longpolling.entrypoints: "web-main"
      traefik.http.routers.recpa-prod-13-0-prod-longpolling.rule:
        "host(`${DOMAIN_PROD}`) && pathprefix(`/longpolling/`)"
      traefik.http.routers.recpa-prod-13-0-prod-longpolling.service: "recpa-prod-13-0-prod-longpolling"
      traefik.http.services.recpa-prod-13-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.recpa-prod-13-0-prod-longpolling.tls: "true"
      traefik.http.routers.recpa-prod-13-0-prod-longpolling.tls.certresolver: "letsencrypt"
      # Forbid crawlers
      ? traefik.http.middlewares.recpa-prod-13-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.entrypoints: "web-main"
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.middlewares:
        recpa-prod-13-0-prod-buffering,
        recpa-prod-13-0-prod-compress,
        recpa-prod-13-0-prod-forbid-crawlers
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.rule:
        Host(`${DOMAIN_PROD}`) && Path(`/web`, `/web/{anything:.*}`, `/website/info`, `/website/info/{anything:.*}`)
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.service: "recpa-prod-13-0-prod-main"
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.tls: "true"
      traefik.http.routers.recpa-prod-13-0-prod-forbidden-crawlers.tls.certresolver: "letsencrypt"

New site labels:

     doodba.domain.main: "my.domain.com"
      traefik.enable: "true"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:my.domain.com;Path:/web{anything:/.*},/website/info{anything:/.*}
      traefik.main-0.frontend.rule: Host:my.domain.com
      traefik.longpolling-0.frontend.rule: Host:my.domain.com;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.fieldservice2021-13-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.fieldservice2021-13-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.fieldservice2021-13-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.fieldservice2021-13-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.fieldservice2021-13-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.fieldservice2021-13-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.fieldservice2021-13-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.rule:
        Host(`my.domain.com`)
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.rule:
        Host(`my.domain.com`)
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.rule:
        Host(`my.domain.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.service:
        fieldservice2021-13-0-prod-longpolling
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.middlewares:
        fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.rule:
        Host(`my.domain.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.service:
        fieldservice2021-13-0-prod-longpolling
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.middlewares:
        fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.rule:
        Host(`my.domain.com`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forbid-crawlers, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`my.domain.com`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forbid-crawlers, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.tls.certResolver:
        letsencrypt

**Comment by Yajo** [comment] 2020-11-27 11:44
This seems a duplicate of #166.

**Closed by Yajo** 2020-11-27 11:44 UTC
